# Generated by Django 5.0.1 on 2025-09-10 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tracking", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Balise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "balise_type",
                    models.CharField(
                        choices=[
                            ("gps", "Balise GPS"),
                            ("vms", "VMS (Vessel Monitoring System)"),
                            ("ais", "AIS (Automatic Identification System)"),
                            ("emergency", "Balise d'urgence"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("maintenance", "En maintenance"),
                            ("error", "Erreur"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("latitude", models.DecimalField(decimal_places=8, max_digits=10)),
                ("longitude", models.DecimalField(decimal_places=8, max_digits=11)),
                ("vessel_name", models.CharField(blank=True, max_length=255)),
                ("frequency", models.CharField(blank=True, max_length=20)),
                ("power", models.CharField(blank=True, max_length=50)),
                (
                    "battery_level",
                    models.IntegerField(
                        blank=True,
                        help_text="Niveau de batterie en pourcentage",
                        null=True,
                    ),
                ),
                (
                    "signal_strength",
                    models.IntegerField(
                        blank=True,
                        help_text="Force du signal en pourcentage",
                        null=True,
                    ),
                ),
                ("last_update", models.DateTimeField(auto_now=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_balises",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["balise_type", "status"],
                        name="tracking_ba_balise__cf077c_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="tracking_ba_created_36acff_idx"
                    ),
                    models.Index(
                        fields=["latitude", "longitude"],
                        name="tracking_ba_latitud_b38195_idx",
                    ),
                ],
            },
        ),
    ]
