# Generated by Django 5.0.1 on 2025-09-10 14:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Zone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(help_text="Nom de la zone", max_length=255)),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Description détaillée de la zone"
                    ),
                ),
                (
                    "zone_type",
                    models.CharField(
                        choices=[
                            ("safety", "Zone de Sécurité"),
                            ("fishing", "Zone de Pêche"),
                            ("restricted", "Zone Restreinte"),
                            ("navigation", "Zone de Navigation"),
                            ("anchorage", "Zone de Mouillage"),
                            ("harbor", "Zone Portuaire"),
                            ("marine_reserve", "Réserve Marine"),
                            ("exclusion", "Zone d'Exclusion"),
                        ],
                        help_text="Type de zone",
                        max_length=20,
                    ),
                ),
                (
                    "zone_shape",
                    models.CharField(
                        choices=[
                            ("circle", "Cercle"),
                            ("polygon", "Polygone"),
                            ("rectangle", "Rectangle"),
                            ("line", "Ligne"),
                        ],
                        default="polygon",
                        help_text="Forme de la zone",
                        max_length=20,
                    ),
                ),
                (
                    "center_latitude",
                    models.DecimalField(
                        decimal_places=8, help_text="Latitude du centre", max_digits=10
                    ),
                ),
                (
                    "center_longitude",
                    models.DecimalField(
                        decimal_places=8, help_text="Longitude du centre", max_digits=11
                    ),
                ),
                (
                    "coordinates",
                    models.JSONField(help_text="Coordonnées GeoJSON de la zone"),
                ),
                (
                    "radius",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Rayon en mètres (pour les cercles)",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "width",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Largeur en mètres",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "height",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Hauteur en mètres",
                        max_digits=8,
                        null=True,
                    ),
                ),
                (
                    "area",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Superficie en m²",
                        max_digits=12,
                        null=True,
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(default=True, help_text="Zone active"),
                ),
                (
                    "is_restricted",
                    models.BooleanField(
                        default=False, help_text="Zone avec restrictions"
                    ),
                ),
                (
                    "max_speed",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Vitesse maximale autorisée (nœuds)",
                        max_digits=5,
                        null=True,
                    ),
                ),
                (
                    "valid_from",
                    models.DateTimeField(
                        blank=True, help_text="Valide à partir de", null=True
                    ),
                ),
                (
                    "valid_until",
                    models.DateTimeField(
                        blank=True, help_text="Valide jusqu'à", null=True
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        default="#3B82F6",
                        help_text="Couleur d'affichage (hex)",
                        max_length=7,
                    ),
                ),
                (
                    "opacity",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.3,
                        help_text="Opacité d'affichage",
                        max_digits=3,
                    ),
                ),
                (
                    "stroke_color",
                    models.CharField(
                        default="#1E40AF", help_text="Couleur du contour", max_length=7
                    ),
                ),
                (
                    "stroke_width",
                    models.IntegerField(default=2, help_text="Épaisseur du contour"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_zones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Zone",
                "verbose_name_plural": "Zones",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["zone_type", "is_active"],
                        name="zones_zone_zone_ty_6329ab_idx",
                    ),
                    models.Index(
                        fields=["-created_at"], name="zones_zone_created_e33e86_idx"
                    ),
                    models.Index(
                        fields=["center_latitude", "center_longitude"],
                        name="zones_zone_center__5c4e4f_idx",
                    ),
                    models.Index(
                        fields=["valid_from", "valid_until"],
                        name="zones_zone_valid_f_d4acf2_idx",
                    ),
                ],
            },
        ),
    ]
