# Generated by Django 5.0.1 on 2025-09-10 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='zone_shape',
            field=models.CharField(choices=[('circle', 'Cercle'), ('polygon', 'Polygone'), ('rectangle', 'Rectangle'), ('line', 'Ligne')], default='polygon', help_text='Forme de la zone', max_length=20),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_latitude',
            field=models.DecimalField(decimal_places=8, help_text='Latitude du centre', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='center_longitude',
            field=models.DecimalField(decimal_places=8, help_text='Longitude du centre', max_digits=11, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='width',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Largeur en mètres', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='height',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Hauteur en mètres', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='area',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Superficie en m²', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='is_restricted',
            field=models.BooleanField(default=False, help_text='Zone avec restrictions'),
        ),
        migrations.AddField(
            model_name='zone',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Vitesse maximale autorisée (nœuds)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='valid_from',
            field=models.DateTimeField(blank=True, help_text='Valide à partir de', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='valid_until',
            field=models.DateTimeField(blank=True, help_text='Valide jusqu\'à', null=True),
        ),
        migrations.AddField(
            model_name='zone',
            name='color',
            field=models.CharField(default='#3B82F6', help_text="Couleur d'affichage (hex)", max_length=7),
        ),
        migrations.AddField(
            model_name='zone',
            name='opacity',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text="Opacité d'affichage", max_digits=3),
        ),
        migrations.AddField(
            model_name='zone',
            name='stroke_color',
            field=models.CharField(default='#1E40AF', help_text='Couleur du contour', max_length=7),
        ),
        migrations.AddField(
            model_name='zone',
            name='stroke_width',
            field=models.IntegerField(default=2, help_text='Épaisseur du contour'),
        ),
    ]
