# Generated by Django 5.0.1 on 2025-09-11 14:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0002_auto_20250910_1650"),
    ]

    operations = []
