# Generated by Django 5.0.1 on 2025-09-11 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0003_auto_20250911_1447"),
    ]

    operations = [
        migrations.AddField(
            model_name="zone",
            name="radius_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Latitude du point de rayon",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="zone",
            name="radius_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Longitude du point de rayon",
                max_digits=11,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="center_latitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Latitude du centre",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="center_longitude",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                help_text="Longitude du centre",
                max_digits=11,
                null=True,
            ),
        ),
    ]
