# Generated by Django 5.0.1 on 2025-09-11 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0004_zone_radius_latitude_zone_radius_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="height",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Hauteur en mètres",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="radius",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Rayon en mètres (pour les cercles)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="zone",
            name="width",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Largeur en mètres",
                max_digits=10,
                null=True,
            ),
        ),
    ]
