# Generated by Django 5.0.1 on 2025-09-11 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("zones", "0005_alter_zone_height_alter_zone_radius_alter_zone_width"),
    ]

    operations = [
        migrations.AlterField(
            model_name="zone",
            name="radius",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                help_text="Rayon en mètres (pour les cercles)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
