# Generated by Django 5.0.1 on 2025-09-10 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_mediafile_like_count_mediacomment_medialike"),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediafile',
            name='uploaded_by',
            field=models.ForeignKey(
                blank=True,
                help_text='Utilisateur qui a uploadé le fichier',
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='uploaded_media',
                to='users.user'
            ),
        ),
    ]
