# Generated by Django 5.0.1 on 2025-09-07 20:24

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DonationGoal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        max_length=200, verbose_name="Titre de l'objectif"
                    ),
                ),
                ("description", models.TextField(verbose_name="Description")),
                (
                    "target_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant cible (FCFA)",
                    ),
                ),
                (
                    "current_amount",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant actuel (FCFA)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Actif")),
                (
                    "deadline",
                    models.DateField(blank=True, null=True, verbose_name="Date limite"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
            ],
            options={
                "verbose_name": "Objectif de donation",
                "verbose_name_plural": "Objectifs de donation",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Donation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "donor_name",
                    models.CharField(max_length=200, verbose_name="Nom du donateur"),
                ),
                (
                    "donor_email",
                    models.EmailField(max_length=254, verbose_name="Email du donateur"),
                ),
                (
                    "donor_phone",
                    models.CharField(
                        blank=True, max_length=20, verbose_name="Téléphone du donateur"
                    ),
                ),
                (
                    "donor_organization",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Organisation"
                    ),
                ),
                (
                    "donation_type",
                    models.CharField(
                        choices=[
                            ("financial", "Don financier"),
                            ("equipment", "Équipement"),
                            ("service", "Service"),
                            ("other", "Autre"),
                        ],
                        default="financial",
                        max_length=20,
                        verbose_name="Type de donation",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Montant (FCFA)",
                    ),
                ),
                (
                    "description",
                    models.TextField(verbose_name="Description de la donation"),
                ),
                (
                    "purpose",
                    models.TextField(
                        blank=True, verbose_name="Objectif de la donation"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "En attente"),
                            ("confirmed", "Confirmée"),
                            ("completed", "Terminée"),
                            ("cancelled", "Annulée"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Statut",
                    ),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="Don anonyme"),
                ),
                (
                    "is_public",
                    models.BooleanField(default=True, verbose_name="Affichage public"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date de création"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Date de mise à jour"
                    ),
                ),
                (
                    "confirmed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de confirmation"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Date de finalisation"
                    ),
                ),
                (
                    "processed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Traité par",
                    ),
                ),
            ],
            options={
                "verbose_name": "Donation",
                "verbose_name_plural": "Donations",
                "ordering": ["-created_at"],
            },
        ),
    ]
